/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.artemis.java-conventions")
    id("com.artemis.github-conventions")
}

dependencies {
    implementation(project(":artemis-odb"))
}

description = "artemis-fluid-core-utility-sources"
