/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.artemis.java-conventions")
    id("com.artemis.github-conventions")
    id("java-gradle-plugin")
}

dependencies {
    implementation(project(":artemis-odb-weaver"))
}

gradlePlugin {
    plugins {
        register("artemis") {
            id = "com.artemis.artemis"
            implementationClass = "com.artemis.ArtemisGradlePlugin"
        }
    }
}

description = "artemis-odb-gradle-plugin"
