/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.artemis.java-conventions")
    id("com.artemis.github-conventions")
}

dependencies {
    implementation("commons-io:commons-io:2.4")
    implementation("com.beust:jcommander:1.35")
    implementation("net.onedaybeard.ecs:matrix-artemis:0.2.0")
    implementation(project(":artemis-odb-weaver"))
}

description = "artemis-odb-cli"
