/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.artemis.java-conventions")
    id("com.artemis.github-conventions")
}

dependencies {
    implementation(project(":artemis-odb"))
    implementation("com.google.guava:guava:20.0")
    implementation("com.squareup:javapoet:1.7.0")
    implementation("org.reflections:reflections:0.9.11")
    implementation("io.github.lukehutch:fast-classpath-scanner:2.0.3")
    implementation("commons-io:commons-io:2.4")
    testImplementation("com.github.javaparser:javaparser-core:3.5.2")
}

description = "artemis-fluid-core"
