/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.artemis.java-conventions")
    id("com.artemis.github-conventions")
}

dependencies {
    testImplementation("org.mockito:mockito-all:1.9.5")
    testImplementation("org.openjdk.jol:jol-core:0.5")
}

description = "artemis-odb"
