name: Build and Publish

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .github/workflows/main.yml

  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Build
        run: ./gradlew build        
      - name: Publish to Github Packages
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
